[platformio]
default_envs = 2in66-development

[base]
description = Base Configuration
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
lib_deps = 
	lvgl/lvgl
    sparkfun/SparkFun ATECCX08a Arduino Library@^1.3.1
build_flags = 
    -DPICO_STDIO_UART
    -DPICO_STDIO_USB
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
    -I include
upload_protocol = picotool
monitor_speed = 115200

[env:i2c_scan]
extends = base
build_flags = 
    ${base.build_flags}
    -DDEBUG_MODE
    -DI2C_SCAN

[env:2in13-lvgl-trace]
extends = base
build_flags = 
    ${base.build_flags}
    -DDEBUG_MODE
    -DEPD_2IN13
    -DLV_USE_LOG=1
    -DLV_LOG_LEVEL=0

[env:2in13-development]
extends = base
build_flags = 
    ${base.build_flags}
    -DDEBUG_MODE
    -DEPD_2IN13
    -DLV_USE_LOG=1
    -DLV_LOG_LEVEL=1

[env:2in13-production]
extends = base
build_flags = 
    ${base.build_flags}
    -DEPD_2IN13

[env:2in66-lvgl-trace]
extends = base
build_flags = 
    ${base.build_flags}
    -DDEBUG_MODE
    -DEPD_2IN66
    -DLV_USE_LOG=1
    -DLV_LOG_LEVEL=0

[env:2in66-development]
extends = base
build_flags = 
    ${base.build_flags}
    -DDEBUG_MODE
    -DEPD_2IN66
    -DLV_USE_LOG=1
    -DLV_LOG_LEVEL=1

[env:2in66-production]
extends = base
build_flags = 
    ${base.build_flags}
    -DEPD_2IN66
