[platformio]
default_envs = 2in13-development

[env:2in13-development]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags = 
    -DPICO_STDIO_UART
    -DPICO_STDIO_USB
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
    -DDEBUG_MODE
    -DEPD_2IN13
;lib_deps =
;    lvgl/lvgl@^9.4.0
upload_protocol = picotool
monitor_speed = 115200

[env:2in13-production]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags = 
    -DPICO_STDIO_UART
    -DPICO_STDIO_USB
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
    -DEPD_2IN13
;lib_deps =
;    lvgl/lvgl@^9.4.0
upload_protocol = picotool
monitor_speed = 115200


[env:2in66-development]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags = 
    -DPICO_STDIO_UART
    -DPICO_STDIO_USB
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
    -DDEBUG_MODE
    -DEPD_2IN66
;lib_deps =
;    lvgl/lvgl@^9.4.0
upload_protocol = picotool
monitor_speed = 115200

[env:2in66-production]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags = 
    -DPICO_STDIO_UART
    -DPICO_STDIO_USB
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
    -DEPD_2IN66
;lib_deps =
;    lvgl/lvgl@^9.4.0
upload_protocol = picotool
monitor_speed = 115200