[platformio]
default_envs = 2in13-development

[base]
description = Base Configuration
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
lib_deps = 
	lvgl/lvgl@^9.4.0
build_flags = 
    -DPICO_STDIO_UART
    -DPICO_STDIO_USB
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
    -I include
upload_protocol = picotool
monitor_speed = 115200

[env:2in13-development]
extends = base
build_flags = 
    ${base.build_flags}
    -DDEBUG_MODE
    -DEPD_2IN13

[env:2in13-production]
extends = base
build_flags = 
    ${base.build_flags}
    -DEPD_2IN13

[env:2in66-development]
extends = base
build_flags = 
    ${base.build_flags}
    -DDEBUG_MODE
    -DEPD_2IN66

[env:2in66-production]
extends = base
build_flags = 
    ${base.build_flags}
    -DEPD_2IN66
